# Generated by Django 4.1.1 on 2022-09-17 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meeting_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeting_app', '0002_meeting_profile_time_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Available Slot',
                'verbose_name_plural': 'Available Slots',
            },
        ),
        migrations.CreateModel(
            name='BookedMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('meeting_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booked Meeting',
                'verbose_name_plural': 'Booked Meetings',
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default=meeting_app.models.generate_random_string, max_length=256, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('available_slots', models.ManyToManyField(related_name='selected_slots', to='meeting_app.availableslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_sharing_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sharing Link',
                'verbose_name_plural': 'Sharing Links',
            },
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
