# Generated by Django 4.1.1 on 2022-09-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0004_alter_sharelink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedmeeting',
            name='user_email',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bookedmeeting',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='client_secret',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_google_acc_linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='refresh_token',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='scopes',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='token_uri',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
