# Generated by Django 4.1.1 on 2022-09-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_app', '0005_bookedmeeting_user_email_bookedmeeting_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharelink',
            name='available_slots',
        ),
        migrations.AddField(
            model_name='sharelink',
            name='available_slots',
            field=models.JSONField(default=list),
        ),
    ]
